# Generated by Django 4.2.9 on 2024-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonproblem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='user_email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
